<a href="https://colab.research.google.com/github/Zhaotai924/Pytorch-Tutorial-Youtube/blob/main/tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
my_tensor = torch.arange(10)
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
#Reshape and View
my_tensor = my_tensor.reshape(2,5)
my_tensor

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [4]:
# Reshape if we don't know the number of items using -1
my_tensor2 = torch.arange(15)
my_tensor2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
my_tensor2 = my_tensor2.reshape(-1,5)
my_tensor2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [6]:
my_tensor3 = torch.arange(10)
my_tensor3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
my_tensor4 = my_tensor3.view(2,5)
my_tensor4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# Difference between reshape and view
# https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch

In [8]:
# Slices
my_tensor5 = torch.arange(10)
my_tensor5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# Grab a specific item
my_tensor5[7]

tensor(7)

In [10]:
# Grab slice
my_tensor6 = my_tensor5.reshape(5,2)
my_tensor6

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [13]:
my_tensor6[:,1]

torch.Size([5])

In [15]:
# Return a column
my_tensor6[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])