<a href="https://colab.research.google.com/github/Zhaotai924/Pytorch-Tutorial-Youtube/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Tensors

*   A torch.Tensors is a multi-dimenstional matrix containing elements of a single data type.






In [2]:
import torch
import numpy as np

# LISTS


In [3]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# NUMPY ARRAYS

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.84292017, 0.22783476, 0.25409673, 0.59483133],
       [0.56412617, 0.24716357, 0.6431117 , 0.25443228],
       [0.02733574, 0.99974008, 0.84781129, 0.27142221]])

In [6]:
np1.dtype

dtype('float64')

# TENSORS


In [17]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.3519,  1.2403,  0.2431,  0.8639],
        [ 1.3699, -0.2880, -0.5884,  1.0160],
        [ 0.2071,  0.8074,  1.1624,  1.0848]])

In [18]:
tensor_2d.dtype

torch.float32

In [13]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [15]:
## Create a tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.8429, 0.2278, 0.2541, 0.5948],
        [0.5641, 0.2472, 0.6431, 0.2544],
        [0.0273, 0.9997, 0.8478, 0.2714]], dtype=torch.float64)