<a href="https://colab.research.google.com/github/Zhaotai924/Pytorch-Tutorial-Youtube/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TENSOR MATH OPERATIONS


*   Add, Substract, Multiply, Divide, Remainders, Exponents
*   Shorthand and uh, Longhand
*   Reassignment




In [20]:
import torch
import numpy as np

In [2]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [3]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [4]:
# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [6]:
# Substraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [7]:
# Sun Function
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [12]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [17]:
 # Mul longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [19]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [18]:
# Div Longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [22]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [24]:
# Remainder Longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [26]:
# Exponents/ power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [27]:
# Another way to write longhand
tensor_a.pow(tensor_b)

tensor([    1,    64,  2187, 65536])

In [28]:
# Reassignment
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [33]:
tensor_a

tensor([1, 2, 3, 4])

In [34]:
# tensor_a = tensor-a + tensor_b
tensor_a.add_(tensor_b) # add_: underscore

tensor([ 6,  8, 10, 12])

In [36]:
tensor_a

tensor([ 6,  8, 10, 12])